// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsApplication.Models;

namespace SportsApplication.Migrations
{
    [DbContext(typeof(SportsApplicationContext))]
    [Migration("20190708130523_Migrate")]
    partial class Migrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SportsApplication.Models.Athletes", b =>
                {
                    b.Property<int>("AthletesID");

                    b.Property<double>("Distance");

                    b.Property<string>("Fitness");

                    b.Property<string>("ParticipantName");

                    b.HasKey("AthletesID");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("SportsApplication.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AthletesID");

                    b.Property<int>("TestsID");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("AthletesID");

                    b.HasIndex("TestsID");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("SportsApplication.Models.Tests", b =>
                {
                    b.Property<int>("TestsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ParticipantCount");

                    b.Property<DateTime>("TestDate");

                    b.Property<string>("TestType");

                    b.HasKey("TestsID");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("SportsApplication.Models.Enrollment", b =>
                {
                    b.HasOne("SportsApplication.Models.Athletes", "Athletes")
                        .WithMany("Enrollements")
                        .HasForeignKey("AthletesID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SportsApplication.Models.Tests", "Tests")
                        .WithMany("Enrollments")
                        .HasForeignKey("TestsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
